
language: node_js
node_js:
  - node
before_deploy:
  - npm run build
after_success:
  - 'bash <(curl -s https://codecov.io/bash)'
deploy:
  skip_cleanup: true
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true
